const colors = {
  light: {
    text: '#FFFFFF',
    tint: '#FF6B00',
    background: '#0B0B1A',
    foreground: '#FFFFFF',
    card: '#141426',
    cardForeground: '#FFFFFF',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A30',
    secondaryForeground: '#FFFFFF',
    muted: '#1E2035',
    mutedForeground: '#8892B0',
    accent: '#FFD700',
    accentForeground: '#0B0B1A',
    destructive: '#FF3D00',
    destructiveForeground: '#FFFFFF',
    border: '#1E2035',
    input: '#1A1A30',
    success: '#22C55E',
    warning: '#EAB308',
    bgmi: '#FF6B00',
    freefire: '#FF2D78',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#FF6B00',
    background: '#0B0B1A',
    foreground: '#FFFFFF',
    card: '#141426',
    cardForeground: '#FFFFFF',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A30',
    secondaryForeground: '#FFFFFF',
    muted: '#1E2035',
    mutedForeground: '#8892B0',
    accent: '#FFD700',
    accentForeground: '#0B0B1A',
    destructive: '#FF3D00',
    destructiveForeground: '#FFFFFF',
    border: '#1E2035',
    input: '#1A1A30',
    success: '#22C55E',
    warning: '#EAB308',
    bgmi: '#FF6B00',
    freefire: '#FF2D78',
  },
  radius: 12,
};

export default colors;
